### ISSUE TITLE
ROM file names transferred to device lose capitalization

### ISSUE THREAD

**Issue by mccartbm90** [prosthetichead/GarlicPress#100]
when transferring a rom to the device (by drag and drop), the file name loses any capitalization (e.g. Wario Land 4 becomes wario land 4)

this does not happen when transferring via file explorer.

not a critical issue, but I like my game names capitalized, and this doesn't seem possible with garlic press (I couldnt find any setting that changes this action).  tried to use the rename button in the UI, but that didn't seem to do anything

**Comment by 00anwi** [comment]
@prosthetichead Is there a reason for the _ToLower()_ on _Path.GetFileName(file).ToLower()_ in the DragDrop event?
Or can I delete it?

```C#
private async void MainForm_DragDrop(object sender, DragEventArgs e)
{
    var system = (GarlicSystem)comboSystems.SelectedItem;
    var files = e.Data?.GetData(DataFormats.FileDrop) as string[];
    foreach (string file in files ?? Enumerable.Empty<string>())
    {
        FileAttributes attr = File.GetAttributes(file);
        if (attr != FileAttributes.Directory)
        {
            txtCurrentTask.Text = "uploading " + file + " for system " + system.name + " to SD " + comboDrive.SelectedIndex + 1;
            Progress<int> progress = new Progress<int>(p => { txtCurrentTask.Text = $"uploading {p}%"; txtCurrentTask.ForeColor = p > 99 ? Color.Green : Color.OrangeRed; });
            await ADBConnection.UploadFileAsync(file, SelectedRomPath + "/" + Path.GetFileName(file).ToLower(), progress, CancellationToken.None);
        }
        else
        {
            MessageBox.Show(file + " apears to be a directory right now GarlicPress does not support uploading directories. ");
        }
    }
    txtCurrentTask.ForeColor = Color.Black;
    txtCurrentTask.Text = "upload complete";
    RefreshBrowserFiles();
}
```

**Comment by prosthetichead** [comment]
Hmm I think it was due to some issues I was having early on with case sensitivity and was removed from other places and not from here. 
It can probably be removed.

**Comment by 00anwi** [comment]
Okay, I deleted it now and added it to the my pull request.
