### ISSUE TITLE
GarlicPress cannot access RG35xxx via path /mnt/mmc/ROMs/ despite device connected (Win10)

### ISSUE THREAD

**Issue by mackonsti** [prosthetichead/GarlicPress#106]
**Describe the bug**
GarlicPress cannot access RG35XX device via ADB despite the latter being connected, apparently with success.
The device is accessible when using https://app.webadb.com/ on browser (with GarlicPress not running).

**To Reproduce**
1. Enable ADB on RG35xx and confirm file `EnableADB` is recorded in MISC partition
2. Reboot RG35xx and wait until Windows 10 signals audibly a connected USB device
3. Make sure it's GarlicOS is actively running on device
4. Launch GarlicPress.exe and see it cannot connect to the device
5. Close/quit GarlicPress.exe, force-quit any `adb` traces in Windows Task Manager
6. Launch https://app.webadb.com/ on browser
7. Access device's SD card in path `/mnt/mmc/ROMs` and browse contents just fine.

**Expected behavior**
GarlicPress.exe should be able to access the device's SD card, from the moment https://app.webadb.com/ on browser can see contents successfully.

**Screenshots**

![GarlicPress](https://github.com/prosthetichead/GarlicPress/assets/1313613/df46f27a-2bd1-4b4a-80ae-5c8efda44952)

![WebAdb](https://github.com/prosthetichead/GarlicPress/assets/1313613/30f55593-926e-4cca-b2ee-6df399f31d16)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Official latest Anbernic Dual Firmware from https://win.anbernic.com/download/270.html

**RG35xx (please complete the following information):**
 - GarlicOS version: **1.4.9** (that is built-in with the official Anbernic System firmware above)
 - Device is reported as "ToyCloud"

**Additional context**
N.B. I have installed (i.e. unzipped and copied) in `C:\Windows\` the files that come from Android **platform-tools_r34.0.5-windows.zip** as the website https://app.webadb.com/ seems to need `adb` in the path. This action was done later, after trying GarlicPress that was not successfully connecting, therefore it is not the root cause. I have rebooted Windows in multiple occasions to directly launch GarlicPress for this reason.

N.B. I have renamed the folder to `ROMs` and it is not `Roms` or `roms` but that should not really make a difference, as the device launches games/ROMs without any issue.

I am not sure if the path of GarlicPress.exe is hard-coded, not sure why it cannot read `/mnt/mmc/ROMs/` when running the latest **Anbernic Dual Firmware** image on SD card (successfully) in **GarlicOS** mode.

**Comment by Evgeny-Usynin** [comment]
Hi. I faced same issue. I also did some investigation. I've found that problem is device model and device name are empty strings are returned by AdbClient. So, here: https://github.com/prosthetichead/GarlicPress/blob/b801c21105fc9d7cb5135c9a5125c73f6c403462/classes/ADBConnection.cs#L65C41-L65C41 if condition is always false.
Hope that helps you to fix the bug.

**Comment by mackonsti** [comment]
Thanks for sharing your findings @Evgeny-Usynin hopefully @prosthetichead can fix this and provide a kind update. However the empty strings do they denote, in your opinion, a non original Anbernic RG35XX device? The store that I got it claimed it is original... could this be the reason for the empty strings? 🤔

**Comment by prosthetichead** [comment]
Thanks for the great investigation guys I will get back to you soon with a fix or a version to test!

**Comment by mackonsti** [comment]
Hi @prosthetichead please know that there's a new version of Android `platform-tools_r34.0.5-windows.zip` you can also integrate in your app and update `adb.exe` at https://developer.android.com/tools/releases/platform-tools

**Comment by Evgeny-Usynin** [comment]
IMHO, that could be related to different RG35xx revision (as I know there are at least 2 revisions of device: battery 2200mah and 2600mah, probably there are some other harware difference between them) or version of GarlicOS.
As I can see, there is hardcoded serial number value in GarlicOS:

> on boot
>     #usb serial
>     write  /data/usb_serialnumber 0123456789ABCDEF

I can see exactly that serial number then I connect my device via ADB.
I think all devices will have that same serial number value.
Probably, it makes sense to modify if condition to implement that fallback case, smth like:
if ((d.Name == "q88_hd" && d.Model == "ToyCloud") || d.Serial == "0123456789ABCDEF")

**Comment by prosthetichead** [comment]
I've done some testing and I have been able to replicate an empty Name and Model. This has been on a cheap old USB C cable. 

I can also replicate the serial 0123456789ABCDEF. 
I'm now adding the ability to change the detected Name, Model and Serial number in the settings as a way to set these to anything your device may be sending out and added a detect button to help identify.

I'm throwing it up as a new Release let me know how you go.

**Comment by Evgeny-Usynin** [comment]
Yes, it works now! Great, thanks a lot! :)

**Comment by mackonsti** [comment]
Hi @prosthetichead thanks for the release, I could not test it earlier, works on my system too! 🙏 Many thanks.
