### ISSUE TITLE
Crashing Windows 10

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [prosthetichead/GarlicPress#16]
Often crashing for me when doing something like update art
windows 10, latest version.
Error dialog:

************** Ausnahmetext **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GarlicPress.ScreenScraper.DownloadMedia(GameResponse game, String mediaType)
   at GarlicPress.GameMediaGeneration.GenerateGameMedia(GameResponse game)
   at GarlicPress.MainForm.UpdateArt(Boolean promptName)
   at GarlicPress.MainForm.btnUpdateArtPrompt_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Private.CoreLib.dll.
----------------------------------------
GarlicPress
    Assembly-Version: 1.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.222.6407.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/System.Windows.Forms.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.222.6407.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Specialized.dll.
----------------------------------------
System.Threading
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Collections.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
AdvancedSharpAdbClient
    Assembly-Version: 2.5.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/System.Configuration.ConfigurationManager.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.ObjectModel.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Thread.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.222.6407.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/Accessibility.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.TypeConverter.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Concurrent.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.dll.
----------------------------------------
System.Memory
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Memory.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Numerics.Vectors.dll.
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/System.Resources.Extensions.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.222.6407.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/System.Drawing.dll.
----------------------------------------
System.Linq
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Linq.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Private.Uri.dll.
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.InteropServices.RuntimeInformation.dll.
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.Process.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Collections.NonGeneric.dll.
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Algorithms.dll.
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Primitives.dll.
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Private.Xml.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Text.RegularExpressions.dll.
----------------------------------------
System.Net.WebClient
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.WebClient.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Text.Encoding.Extensions.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.dll.
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Serialization.Formatters.dll.
----------------------------------------
System.Xml.XmlSerializer
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Xml.XmlSerializer.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.Primitives.dll.
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Sockets
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.Sockets.dll.
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.Tracing.dll.
----------------------------------------
System.Text.Json
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Text.Json.dll.
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Emit.Lightweight.dll.
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Primitives.dll.
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Emit.ILGeneration.dll.
----------------------------------------
System.Text.Encodings.Web
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Text.Encodings.Web.dll.
----------------------------------------
System.Runtime.Intrinsics
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Intrinsics.dll.
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Loader.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 6.0.2.0.
    Win32-Version: 6.0.222.6407.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.2/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Net.Requests
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.Requests.dll.
----------------------------------------
System.Net.WebHeaderCollection
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.WebHeaderCollection.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Threading.ThreadPool.dll.
----------------------------------------
System.Net.Http
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.Http.dll.
----------------------------------------
System.Web.HttpUtility
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Web.HttpUtility.dll.
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.DiagnosticSource.dll.
----------------------------------------
System.Net.Security
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.Security.dll.
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.X509Certificates.dll.
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Overlapped.dll.
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Net.NameResolution.dll.
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Principal.Windows.dll.
----------------------------------------
System.Security.Claims
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Claims.dll.
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Encoding.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 6.0.0.0.
    Win32-Version: 6.0.222.6406.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Immutable.dll.
----------------------------------------

************** JIT-Debuggen **************

**Comment by prosthetichead** [comment]
Struggling to reproduce this.
What system and file name for the game is it searching for when it crashes?

**Comment by prosthetichead** [comment]
I think I worked out what this issue is tonight when fixing some issues with the way media is retrieved,
Could you try it again now with the latest release please?

**Comment by prosthetichead** [comment]
@PhilippSPOTTERON 
Going to close this issue if you're still having this problem please comment and we can reopen it.
