### ISSUE TITLE
AdbWinApi.dll was not found

### ISSUE THREAD

**Issue by MitchRuns** [prosthetichead/GarlicPress#2]
When running GarlicPress.exe I get an error stating that AdbWinApi.dll is missing. When clicking OK I get a second error stating another error code (-1073741515). By clicking okay again the software will launch with the bottom right stating "ADB Error"

I attempted to manually add the dll and I was able to launch without the error, but the software shows "No Device"

1. Run GarlicPress.exe
2. See error

![m9578obyfF](https://github.com/prosthetichead/GarlicPress/assets/23586387/cc27fdef-eff5-40a7-9fff-b918230f0b5d)

![GarlicPress_o1LegFnAT4](https://github.com/prosthetichead/GarlicPress/assets/23586387/5d80bf87-0b05-4178-b308-dbe0865a5e02)

Running on Windows 10 Version 10.0.19045 Build 19045

**Comment by prosthetichead** [comment]
Sorry! looks like I forgot to include 2 dll files with ADB.EXE. 
I will repackage it up now and hopefully you can try again!

**Comment by MitchRuns** [comment]
Thank you! I will try it as soon as I see the files available. As of now I don't see them in the current release.

**Comment by prosthetichead** [comment]
Sorry I ended up dashing to work before pushing up the replacement. Glad you got it working and thank you for the issue submissions! These are now in release 20230718.
