### ISSUE TITLE
Add Custom Artwork not on screen scraper

### ISSUE THREAD

**Issue by RTEMPS** [prosthetichead/GarlicPress#29]
Would be great to add custom art work for games not on screen scraper. (I.E. romhacks)

**Comment by RattyBiscuit** [comment]
I second this - I have really enjoyed Apotris, but have to manually create the mix when I use Skraper

**Comment by prosthetichead** [comment]
Could windows defender or a another firewall/virus scanner be blocking it from internet access?

**Comment by fariaboy** [comment]
yeah this would be super helpful, when I scrape for Game boy color games for example with garlic press I end up with french cover arts on pokemon gold, silver and crystal but i have found english ones on screenscraper i could use to replace the french ones if this feature could be added.

**Comment by prosthetichead** [comment]
@RattyBiscuit  oops sorry I posted that comment on the wrong issue.
that will teach me for trying to reply from my phone on the bus..
