### ISSUE TITLE
When updating art, I don't see a way to cancel the process.

### ISSUE THREAD

**Issue by BenBurum** [prosthetichead/GarlicPress#31]
**Is your feature request related to a problem? Please describe.**
I'm currently updating the box art for about 2500 CPC games and it's prompting to skip every time it doesn't recognize a file name.  I believe there's an option to change that prompt, but I don't see an option to cancel the current update process.  It would be nice if there was a button to cancel.

Alternatively, do you know if it would hurt anything to just force-quit the program and start over?  I doubt that would cause any harm but I would feel better if there were an actual cancel button I could press.

**Comment by prosthetichead** [comment]
This has been added to the latest release!
