### ISSUE TITLE
Error Reading Skin Settings Json with Liquid Crystal Theme

### ISSUE THREAD

**Issue by delacroix17** [prosthetichead/GarlicPress#33]
Starting up GarlicPress gives me an error and I cannot see any roms from my device. 

Error says: 
CFW/skin/settings.json skin settings can not be loaded.
Preview will not display text position skin settings tool will not function.
Please report the skin you are using to issues in the About. 
Error Text: 
""" is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 6 | BytePositionInLine: 1. 
[image](https://imgur.com/a/Sn4Z6LG)

- Windows 11
- GarlicOS version: 1.4.9
- Liquid Crystal theme (https://www.patreon.com/posts/83760135)

I might have edited my settings.json to fit images better. This is what is in my settings.json file:

{
	"color-guide": "#1e2329",
	"color-inactive": "#747870",
	"color-active": "#1e2329",
	"color-favorite-inactive": "#3f7fa0",
	"color-favorite-active": "#1e2329"
	"main-menu-text-visibility": true,
	"guide-button-text-visibility": true,
	"text-alignment": "left",
	"text-margin": 352,
	"recent-label": "~",
	"favorites-label": "~",
	"consoles-label": "~",
	"retroarch-label": "~",
	"rtc-label": "RTC",
	"navigate-label": "~",
	"open-label": "~",
	"back-label": "~",
	"favorite-label": "~",
	"remove-label": "~",
	"on-label": "ON",
	"off-label": "OFF",
	"am-label": "AM",
	"pm-label": "PM",
	"year-label": "YY",
	"month-label": "MM",
	"day-label": "DD",
	"hour-label": "HH",
	"minute-label": "MM",
	"meridian-time-label", "MT",
	"title-label": "%s"
	"empty-label": "Should you favorite games? Yeah man!",
}

**Comment by prosthetichead** [comment]
GarlicOS seems very insensitive for json structure and will let you break all sorts of JSON rules which garlicpress can't support.

based on the JSON you have posted I think you are missing a  "  ,  "  on the second to last line 
if you replace this line with
`"title-label": "%s",`

does that fix the issue?

**Comment by prosthetichead** [comment]
on second viewing  line 5 is also missing a , 
it should be
`"color-favorite-active": "#1e2329", `

**Comment by delacroix17** [comment]
Yes that fixed the error. There were a couple other things like
"meridian-time-label", "MT", → meridian-time-label": "MT", 
and taking out the last comma in the second to last line.

**Comment by prosthetichead** [comment]
awesome!
I will close this issue as its working now.
