### ISSUE TITLE
support roms in root of second sd card 

### ISSUE THREAD

**Issue by Un4GivNX** [prosthetichead/GarlicPress#34]
**Describe the bug**
Windows 10, both light and dark theme.
GarlicOS 1.4.9
Booting my 35xx, connected via usb, enableADB.
GarlicPress bottom right corner has a green text "RG35xx".
The left panel where the games should be listed is completly black. I selected the SD Card 2 drives where the roms are. I selected various systems with no visual changes. The left panel is always black.
![image](https://github.com/prosthetichead/GarlicPress/assets/32805311/a0269b31-df91-4bee-b001-61ebebdedc1b)

![image](https://github.com/prosthetichead/GarlicPress/assets/32805311/1d8b1013-c091-413e-a554-1922809050aa)

**Comment by prosthetichead** [comment]
on your second SD card, are your games in the root of the drive or in a folder called Roms?

**Comment by Un4GivNX** [comment]
Something like that, games are seen and playable on the console
sd2_root://GBA/*
sd2_root://SFC/*

**Comment by Un4GivNX** [comment]
Moved every rom folders under /Roms/, it works now!

**Comment by prosthetichead** [comment]
Awesome it's working for you now!

Going to reopen this issue and look at a way of being able to support roms in the root and roms in a roms sub folder on the second sd card.
