### ISSUE TITLE
Application won't load when RG35xx is already connected.

### ISSUE THREAD

**Issue by slapjackios** [prosthetichead/GarlicPress#4]
I just used the program to upload a couple of games on a freshly flashed card, then exit the program and tried to relaunch it, but it just showed me a red then green onion on my taskbar (next to the clock) then it disappeared after a couple of seconds.

Windows 11

stock+garlic_test_20230629_1 (dual boot)

**Comment by prosthetichead** [comment]
Can you try this again with release 20230718? I think it may have been released to issue #5

**Comment by PhilippSPOTTERON** [comment]
Confirmed. But also unplugging and replugging does not help.
Basically it needs currently to unzip Garlic Press fresh each time you want to start it.

**Comment by slapjackios** [comment]
> Confirmed. But also unplugging and replugging does not help. Basically it needs currently to unzip Garlic Press fresh each time you want to start it. Win10, latest version

It works for me when I unplug. It just starts minimized and you have to double click it from the Taskbar.

**Comment by prosthetichead** [comment]
@slapjackios 
Going to close this issue if you're still having this problem please comment and we can reopen it.
