### ISSUE TITLE
Dual Boot Image won't start up

### ISSUE THREAD

**Issue by radioraheem** [prosthetichead/GarlicPress#43]
**Describe the bug**
I added the EnableADB file to the memory card in the appropriate place and afterwards the dual boot OS card image will not start up.  Removing the file resulted in the same behavior.  I'm going to flash the regular GarlicOS image and re-test. 

**To Reproduce**
1. Follow instructions to created EnableADB file on appropriate sd card path
2. Reinsert card into RG35XX and power it up
3.  Start up is stuck on the boot image, no adb response

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**RG35xx (please complete the following information):**
 - GarlicOS version: Dual Boot image from Anbernic

**Comment by radioraheem** [comment]
Quick update:  I flashed the regular GarlicOS image and GarlicPress works fine.  Thank you!

**Comment by prosthetichead** [comment]
Glad its working for you now.
Closing this issue but I do think I need to put the Dual Boot on a SD card to do some testing myself as it seems to have a few quirks.
