### ISSUE TITLE
GarlicPress will not load settings.json for Anbernic's new dual system firmware.

### ISSUE THREAD

**Issue by darth-crunchus** [prosthetichead/GarlicPress#48]
**Describe the bug**
GarlicPress will not load CFW/skin/settings.json on Anbernic's new dual system firmware.

**To Reproduce**
1. Flash Anbernic Dual system FW (GarlicOS + Anbernic Stock)
2. Start GarlicPress
3. Plug RG35XX in

**Expected behavior**
Expected the CFW/skin/settings.json file to be loaded

**Screenshots**
![Screenshot 2023-08-04 143650](https://github.com/prosthetichead/GarlicPress/assets/27889886/5d756d52-1202-416f-ac38-bda7473510a9)

**Desktop (please complete the following information):**
 - OS: Window 11
**RG35xx (please complete the following information):**
 - GarlicOS version: 1.4.9 Anbernic

**Additional context**
Theme used is the default "theme-2023 mslug"

**Comment by prosthetichead** [comment]
in garlicpress directory can you please open the file assets/skinSettings.json and copy and paste the contents into a post on this issue.

**Comment by darth-crunchus** [comment]
GarlicPress/assets/settings.json:

{
	"text-alignment": "left",
	"text-margin": 322
	"color-guide": "#ffffff",
	"color-inactive": "#9e9e9e",
	"color-active": "#ffffff",
	"color-favorite-inactive": "#be6f1a",
	"color-favorite-active": "#fe8503",
	"main-menu-text-visibility": true,
	"guide-button-text-visibility": true,
}

**Comment by darth-crunchus** [comment]
Also, I tried a standalone GarlicOS installation, and that seems to work fine, so it's definitely something with Anbernic's implentation.

**Comment by prosthetichead** [comment]
the json file is invalid

Line 3 needs a , on the end


```
{
"text-alignment": "left",
"text-margin": 322
"color-guide": "#ffffff",
"color-inactive": "#9e9e9e",
"color-active": "#ffffff",
"color-favorite-inactive": "#be6f1a",
"color-favorite-active": "#fe8503",
"main-menu-text-visibility": true,
"guide-button-text-visibility": true,
}
```

**Comment by p42o** [comment]
Just worked through this using ChatGPT (note, I'm kind of a noob) and was able to resolve it! It seems like the settings.json file missing a comma is no longer the issue. For me, it was looking for the settings.json file in the directory GarlicPress was running and it was not there. After going into the /GarlicPress/assets there was no /skin folder. Created a /skin folder, copied the settings.json from the RG35XX SD card, and it worked! 

Here's my GPT convo if anyone's interested in how I used it to both find this post + troubleshoot until resolved. https://chat.openai.com/share/41d07169-97e1-41d0-b5d5-e88ca06438a2
