### ISSUE TITLE
Game art layout profiles

### ISSUE THREAD

**Issue by ekaschyk** [prosthetichead/GarlicPress#52]
It would be helpful to be able to save different game art layouts as “layout profiles” or “custom mixes”. 
After setting up a complex multilayer layout I found myself wanting to try something completely different.  I had to screenshot my current layout and reenter the settings from scratch to come back to it. 
Another use case is saving tweaks of a similar layout for different systems. Since aspect ratios vary from system to system it may be necessary to adjust parameters. If you ever add a new game and want to scrape the art the user could just select a named profile instead of keeping track of all those small differences.

**Comment by prosthetichead** [comment]
With the new art loading screen this is defiantly something I want to work on soon I want to try combine this enhancement and #58 together in a full rework of the layouts managment.
