### ISSUE TITLE
Skraper mixes

### ISSUE THREAD

**Issue by SmooQ84** [prosthetichead/GarlicPress#58]
Would it be possible to add support for mix files from skraper (skraper.net)? They are in XML format. This is quite a popular artbox downloader. I already have prepared files that I can't translate into the format of your program.
[example.xml.txt](https://github.com/prosthetichead/GarlicPress/files/12269213/example.xml.txt)

**Comment by prosthetichead** [comment]
This is a great idea! but is a bit tricky as it has more options then garlicpress does. 
I do want to improve the layouts though and add a way of saving them and using different ones easily. 

I will look closer at this when I look at improving the layout management

**Comment by RattyBiscuit** [comment]
It would be great to support the features like Skraper - I use an overlay on my images to fade them out using a gradient which I think looks pretty nice

![WhatsApp Image 2023-08-10 at 11 29 32](https://github.com/prosthetichead/GarlicPress/assets/7528696/930291aa-e4ee-493c-ab91-0b5d3399792e)

[DarkMix.xml.txt](https://github.com/prosthetichead/GarlicPress/files/12311772/DarkMix.xml.txt)
