### ISSUE TITLE
Updating Game Art memory error

### ISSUE THREAD

**Issue by devofreck** [prosthetichead/GarlicPress#81]
**Updating Game Art**

**To Reproduce**
1. I chose my GameBoy Advance Directory
2. Selected them all
3. Chose Update Art

**Expected behavior**
I am able to update no problem on version GarlicPress.0.0.2307.261

**Screenshots**
![Screenshot 2023-08-14 112135](https://github.com/prosthetichead/GarlicPress/assets/61300787/75f81c0e-b91e-4adc-bfc3-0f560773c581)
 - OS: Windows 11
 - GarlicOS version: 1.4.9

**Comment by prosthetichead** [comment]
Can you update garlicpress?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prosthetichead** [comment]
Sorry I should wake up more before I reply! I will check this out after work tonight.

**Comment by prosthetichead** [comment]
Can you paste the text from the error box into here also?

**Comment by devofreck** [comment]
i am so sorry for making you think there was something wrong. I must have input my password incorrectly for screescraper.fr
I entered the credentials again, and its working as expected!  I will close out the issue
![Screenshot 2023-08-14 165536](https://github.com/prosthetichead/GarlicPress/assets/61300787/4e5d4aa6-00f2-499f-b302-a035aba8802e)

**Comment by prosthetichead** [comment]
All good!!! It is interesting this had that error though. I'm thinking I need to add a password check.
