### ISSUE TITLE
Bypassing "Game Not Found" Scrape Error in Media Editor for using Only Local Media

### ISSUE THREAD

**Issue by Salitance** [prosthetichead/GarlicPress#92]
Hi there. When going to add only local media to a given ROM using the new Media Editor, you cannot bypass the scrape attempt, even if you do not have any scraping (aka a layer style intended to pull from ScreenScraper) added to the used Media Layer Collection. This prevents adding solely custom/uploaded art without a workaround. 

**i.e.** I have a Pokemon ROM Hack. I found a custom Box Art for it online. I can add and size it appropriately using the new Media Editor and save it as a Media Layer Collection. When you go to update, it still calls for a scrape even though it's only one layer which is Local Art. Because the ROM doesn't exist formally, it hits you with Game Not Found and doesn't apply the Local Art. 

### **My workaround:** 
Saving the Media Layer Collection and returning to the main program page. Selecting Update Art, which allows you to change the search text for Scraping, and selecting the Local Art Media Layer Collection. So for my example, I pretended the game was Pokemon Emerald, so the Scraping happened, and then it just default to my preset custom box art and looked great / as intended originally.

### Potential Solution?
Either allow another field in the Media Editor which allows you to scrape under a different Search string, like the Update Game Art window (more of a short-term fix for my issue, but added functionality does help for legitimate ROMs that have a hard time with searches)

Or let us Bypass having to Scrape on Update in the Media Editor so we can put custom art for custom ROMs or what have you. 

Overall I love and appreciate the new update and the program in general, it's streamlined most things for me. Thank you for your work and time.

**Comment by prosthetichead** [comment]
Fixed by https://github.com/prosthetichead/GarlicPress/pull/95
