### ISSUE TITLE
Update Art Menu - Too Big/Can't Resize, thus Not Visible on Screen

### ISSUE THREAD

**Issue by CartCollector** [prosthetichead/GarlicPress#93]
Bug:
When I go to a game/selection and press UPDATE ART, the art update window appears.  However, options/info on the right side of the window is inaccessible, as the sorting menu takes up most of the window space.  Attempting to resize the window keeps the sorting table present, but doesn't allow me to view the preview/options.

Reproduce:
Go to any title. Click "Update Art."

**Screenshots**
![menu issue](https://github.com/prosthetichead/GarlicPress/assets/112233619/3e57884f-66f4-40fe-b8d2-a85651677a5c)

Win 11, GarlicOS 1.4.9

My monitor is set to 1600x900 at the moment... lower resolutions make the problem worse.  Earlier versions of Garlicpress had no issue.

If I try to expand the window to a larger size, I still can't view more of the settings/previews...

![menu issue2](https://github.com/prosthetichead/GarlicPress/assets/112233619/bc39f81a-69de-43d5-ad8a-096734a80783)

**Comment by prosthetichead** [comment]
Could you please try this again in the latest release?

**Comment by CartCollector** [comment]
So.... there is good and bad news.

The GOOD news is that the window sizes seem to be fixed now.

The bad news is that when I click on any individual title for a preview in GarlicPress... I get a "Index was outside the bounds of the array" error.  This seems to happen across all my systems, not just the ones with the most titles.

If I -try- to update the art... everything seems to work UNTIL GP gets to the "generating art stage" -- at which point it crashes with the "index was outside the bounds of the array" error.

Should I submit this as a new error?

**Comment by prosthetichead** [comment]
sorry yeah would be best if you can submit as a new issue if you can.
I will close this issue as the original issue is fixed but yeah if you can submit a new issue with some screenshots that would help a lot
