### ISSUE TITLE
Roms not deleting 

### ISSUE THREAD

**Issue by mharos** [prosthetichead/GarlicPress#94]
**Describe the bug**
Roms not being deleted when using delete option.

**To Reproduce**
1. Select rom to be deleted
2. Click on delete
3. Click yes on "Are You Sure?"

**Expected behavior**
For the selected rom to be deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - RG35xx
 - GarlicOS version: 1.4.9

Not sure if this is something I've done wrong or a genuine bug. Have tried on 2 different PCs and having the same problem. Rom list refreshes after confirming delete but the rom remains there.

Edited to note the delete feature is working fine in version 0.0.2308.061

**Comment by 00anwi** [comment]
I have found the bug and fixed it.
Will probably be in next release.

**Comment by mharos** [comment]
Great! Thanks very much!
