### ISSUE TITLE
ROMs not visible in GarlicPress (but device visible)

### ISSUE THREAD

**Issue by MrKeggy** [prosthetichead/GarlicPress#98]
Despite enabling ADB, the ROMs are not visible in GarlicPress, but the device itself is (name appears in bottom right corner).

I have spent all day trying to figure this out by changing things one by one, like:
- Using my Windows 11 laptop instead of my Windows 10 Desktop;
- Using a USB-C to USB-C cable (on laptop) instead of a USB-C to USB;
- Trying 3 different cables total;
- Trying a different USB port;
- Plugging/unplugging my device while GarlicPress was already open, and while it wasn't;
- Putting the program directly on C:\ instead of on my desktop;
- Launching as administrator.

GarlicPress actually worked for all of 10 minutes (after struggling with the same issue since the day before) and I managed to change half of my box arts (though they were not visible on the app's preview screen, but they work on my device), but when I adjusted the text offset in the skin options (which worked), after rebooting, the ROMs weren't visible anymore, and now no matter what I do, it won't work

My theory is that GarlicPress can only access my SD Card 1 (system) (since I can still change skin options and use commands in the console) and not my SD Card 2 for ROMs, which contains the box arts that I managed to add before it stopped working.

Sorry for the wall of text, I tried to put as many details as I could to compensate for the lack of any error message.

- RG35xx
 - GarlicOS version: 1.4.9
![(Screenshot)](https://github.com/prosthetichead/GarlicPress/assets/1348998/bd1057a4-f30b-4fb0-9ef6-ca77bac17f41)

Thank you!

**Comment by prosthetichead** [comment]
System rom folders on SD 2 can be in a Roms folder or on the root of the SD 
Depending on which setup you use there is a setting in File->Settings 

if you have a Roms folder the "Rom System Folders on Root of SD card 2" setting should be off
For example if your nes rom paths are "/roms/nes/romName.nes"

If you have a Nes folder directly on the root than the "Rom System Folders on Root of SD card 2" setting should be on
For example if your nes rom paths are "/nes/romName.nes"


![image](https://github.com/prosthetichead/GarlicPress/assets/1934681/2d51711c-c92c-471b-bc30-6cf5a9ec322a)

**Comment by MrKeggy** [comment]
Thank you, and my apologies, this fixed it! I don't remember changing that setting so it's a bit strange that it somehow worked (wonkily) for a bit, but now everything works perfectly (love the new update too!).
