### ISSUE TITLE
Error When Viewing Art (Index was outside the bounds of the array)

### ISSUE THREAD

**Issue by CartCollector** [prosthetichead/GarlicPress#99]
GarlicPress.0.0.2310.011

In the GarlicPress window, clicking on any title brings up an error dialog. 

I sometimes get the SAME error message when attempting to download art for "all" in a system -- but I can't be sure what's triggering it.  The "preview" screen (during scraping) never shows a preview. If I try to cancel a job, after a few moments it crashes with the index error.
No image files appear to be being sent to the RGXX -- the images are generated and sitting in the TEMP directory, though, with "us1981mxrbv" type names, but they never appear to be renamed and sent to the system.

Error: "Unhandled exception has occurred in your application ... index was outside the bounds of the array."

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GarlicPress.GameMediaGeneration.DrawGameTexts(Graphics graphics, List`1 games, String selectedGame) in C:\Users\ashle\source\repos\GarlicPress\classes\GameMediaGeneration.cs:line 276
   at GarlicPress.GameMediaGeneration.OverlayImageWithSkinBackground(Bitmap imageToOverlay, GarlicSystem selectedSystem, List`1 games, String selectedGame) in C:\Users\ashle\source\repos\GarlicPress\classes\GameMediaGeneration.cs:line 199
   at GarlicPress.MainForm.UpdateImageFromDevice(FileStatistics item) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 212
   at GarlicPress.MainForm.fileListBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 192
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Desktop (please complete the following information):**
 - OS: Win11

**RG35xx (please complete the following information):**
 - GarlicOS version:1.4.9

**Comment by CartCollector** [comment]
![error-01](https://github.com/prosthetichead/GarlicPress/assets/112233619/99575c48-bb69-4692-afd7-ff24af2dc4a3)

**Comment by Zeudan** [comment]
I have the same issue on W10

**Comment by 00anwi** [comment]
Do you what themes you are running in GarlicOS? @CartCollector @Zeudan 

I think I found the issue but want to test it.

**Comment by Zeudan** [comment]
> Do you what themes you are running in GarlicOS? @CartCollector @Zeudan
> 
> I think I found the issue but want to test it.

Yes I have

**Comment by 00anwi** [comment]
> > Do you what themes you are running in GarlicOS? @CartCollector @Zeudan
> > I think I found the issue but want to test it.
> 
> Yes I have

Could you send me a link to the theme? So I can test?

**Comment by 00anwi** [comment]
> It's NES Action Set https://www.rg35xx.com/?sdm_process_download=1&download_id=1073

Thank you!

**Comment by CartCollector** [comment]
> Do you know what themes you are running in GarlicOS? @CartCollector @Zeudan
> 
> I think I found the issue but want to test it.

I'm using the "default" theme?  I've never tweaked anything in the themes...

**Comment by ballistic90** [comment]
I have this same issue when I try and view art from GarlicPress or try to scrape any game. I am also not using any themes.

**Comment by harun911** [comment]
Can confirm, I'm also running into this issue. I don't use any skins and it's the first time I'm using this app. The device connects, but when clicking a game in the list this error is thrown and there is no preview visible.

**Comment by Everett1954** [comment]
Confirm with Garlic 149 error keeps popping up cannot view artwork and after "processing artwork, I get the error and when i hit continue it does nothing. using default theme. No artwork created or uploaded.

**Comment by Everett1954** [comment]
Hi, Will a new version of GarlicPress be posted that fixes these error? Regards,Everett Sent from Mail for Windows From: prostheticHeadSent: Tuesday, November 7, 2023 6:37 AMTo: prosthetichead/GarlicPressCc: Everett1954; CommentSubject: Re: [prosthetichead/GarlicPress] Error When Viewing Art (Index was outside the bounds of the array) (Issue #99) Closed #99 as completed via 102fdac.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by prosthetichead** [comment]
Yes I just need to package it up for release.
